openapi: 3.0.0
info:
  title: DanaVered
  version: '1.0'
  description: |-
    name: OpenWeatherMap API
    version: 2.5
    API description: Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.
  contact:
    name: Support
    url: 'https://openweathermap.org/api'
    email: some_email@gmail.com
  termsOfService: 'Terms of service URL: https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
  - url: ''
    description: ''
  - url: ''
    description: ''
paths:
  /Weather:
    get:
      summary: Weather
      tags:
        - Weather endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Coord:
                    type: object
                    properties:
                      Ion:
                        type: number
                        description: This is Longtitute
                      lat:
                        type: string
                        description: This is Latitude
                  Cod:
                    description: This is Cod
                    type: number
                  name:
                    type: string
                    description: This is Name
                  Id:
                    type: number
                    description: This is ID
                  sys:
                    type: object
                    properties:
                      type:
                        type: number
                      Id:
                        type: number
                      Country:
                        type: string
                      Sunrise:
                        type: number
                        description: This is Subrise
                      Sunset:
                        type: number
                        description: This is Subset
                      dt:
                        type: number
                        description: This is Dt
                  Clouds:
                    type: object
                    properties:
                      all:
                        type: number
                  Wind:
                    type: object
                    properties:
                      Speed:
                        type: number
                        description: This is Speed
                      Deg:
                        type: number
                        description: This is Degrees
                      Visibility:
                        type: number
                        description: This is Visibility
                  Main:
                    type: object
                    properties:
                      Temp:
                        type: number
                        description: This is Temp
                      feels_like:
                        type: number
                        description: This is Feels Like
                      Temp_min:
                        type: number
                        description: This is Tem Min
                      Temp_max:
                        type: number
                        description: This is Temp Max
                      Pressure:
                        type: number
                        description: This is Pressure
                      Humidity:
                        type: number
                        description: This is Humidity
                      Base:
                        type: string
                        description: This is Base
                  Weather:
                    type: array
                    description: This is a Weather Array Object
                    items:
                      type: object
                      properties:
                        Id:
                          type: number
                          description: This is Weather ID
                        Main:
                          type: string
                          description: This is Weather Main
                        Description:
                          type: string
                          description: This is Weather Description
                        Icon:
                          type: string
                          description: This is Weather Icon
              examples: {}
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      operationId: get-Weather
      parameters:
        - schema:
            type: string
          in: query
          name: Zip
          description: Zip Description
        - schema:
            type: string
          in: query
          name: Units
        - schema:
            type: string
          in: query
          name: q
        - schema:
            type: string
          in: query
          name: id
        - schema:
            type: string
          in: query
          name: lat
        - schema:
            type: string
          in: query
          name: lon
        - schema:
            type: string
          in: query
          name: lang
        - schema:
            type: string
          in: query
          name: mode
        - schema:
            type: string
          in: query
          name: appid
      description: Gets weather info
      security:
        - app_id: []
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Unauthorized_Response'
          multipart/form-data:
            schema:
              type: object
              properties: {}
          text/html:
            schema:
              type: object
              properties: {}
          text/plain:
            schema:
              type: object
              properties: {}
          application/EDI-X12:
            schema:
              type: object
              properties: {}
          application/EDIFACT:
            schema:
              type: object
              properties: {}
        description: ''
    parameters: []
components:
  schemas:
    Unauthorized_Response:
      title: Unauthorized_Response
      type: object
      properties:
        Cod:
          type: integer
        Message:
          type: string
      required:
        - Cod
        - Message
      x-examples:
        example-1:
          Cod: 0
          Message: string
  securitySchemes:
    app_id:
      type: apiKey
      in: query
      name: appid
tags:
  - name: Weather endpoints
