openapi: 3.0.0
info:
  title: DanaVered
  version: '1.0'
  description: |-
    name: OpenWeatherMap API
    version: 2.5
    API description: Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.
  contact:
    name: Support
    url: 'https://openweathermap.org/api'
    email: some_email@gmail.com
  termsOfService: 'Terms of service URL: https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
  - url: ''
    description: ''
  - url: ''
    description: ''
paths:
  /Weather:
    get:
      summary: Weather
      tags:
        - Weather endpoints
      responses: {}
      operationId: get-Weather
      security:
        - app_id: []
      parameters:
        - schema:
            type: integer
          in: query
          name: wind
          description: Wind Description
      description: Gets weather info
    parameters: []
components:
  schemas: {}
  securitySchemes:
    app_id:
      type: apiKey
      in: query
      name: appid
tags:
  - name: Weather endpoints
